### ISSUE TITLE
Additional space in the project description link. 

### ISSUE THREAD

**Issue by bogren** [segment-integrations/analytics-ios-integration-localytics#17]
There is an additional link in the project description. The result is a broken link. Solution: remove the space 🙂

<img width="558" alt="screen shot 2017-08-02 at 13 27 09" src="https://user-images.githubusercontent.com/2457281/28871771-590ad6a2-7786-11e7-9982-07c98803e21b.png">

**Comment by ladanazita** [comment]
Hi @bogren ,

Thanks for catching this. Just updated it without the space.
