### ISSUE TITLE
Localytics v5 support

### ISSUE THREAD

**Issue by sstigler** [segment-integrations/analytics-ios-integration-localytics#23]
Localytics iOS SDK v5.0.0 includes several nice-to-have changes: https://docs.localytics.com/dev/sdk-changelog.html#developers-sdk-changelog-ios

Can you please update this integration to provide support for that version of the SDK?

**Comment by ladanazita** [comment]
@sstigler  Thanks for the heads up! Let me look into this — if there are no major api changes this should be a quick update.

Thanks!
Ladan

**Comment by sstigler** [comment]
Thanks @ladanazita ! We have reached out to the customer success team as well. I'll let them know you're looking into this. Looking forward to hearing from you!

Sam

**Comment by sstigler** [comment]
Thanks!

**Comment by sstigler** [comment]
@ladanazita Can this issue now be closed?

**Comment by ladanazita** [comment]
@sstigler Thanks — this is live but looks like @divbyzero found something here that also needs to be updated. Let me scope out his work and then will asses if this can be marked as complete

**Comment by sstigler** [comment]
Okay, thanks @ladanazita . I'll wait to hear from you.

**Comment by sstigler** [comment]
@ladanazita I see that you gave a thumbs-up above... does that mean that this can be marked as complete?
