### ISSUE TITLE
Incompatible with use_frameworks!

### ISSUE THREAD

**Issue by mrchristopher124** [segment-integrations/analytics-ios-integration-localytics#4]
If your Podfile has use_frameworks! enabled, when you include this pod and run 'pod install' you get the following error: "[!] The 'Pods' target has transitive dependencies that include static binaries: (...)"

**Comment by f2prateek** [comment]
Yes this is a limitation of CocoaPods (also discussed in this thread https://github.com/segment-integrations/analytics-ios-integration-google-analytics/issues/3#issuecomment-203112419).

Here are the suggested workarounds to https://github.com/segment-integrations/analytics-ios-integration-google-analytics/issues/3#issuecomment-203115637

**Comment by mrchristopher124** [comment]
OK thanks I'll take a look :)
