### ISSUE TITLE
Localytics iOS 4.0.0 Support

### ISSUE THREAD

**Issue by mrchristopher124** [segment-integrations/analytics-ios-integration-localytics#9]
A couple of Localytics APIs have changed with their 4.0.0 Library:

https://docs.localytics.com/dev/ios.html#migrating-v3-to-v4-ios

Most notably around push notification handling and setting a custom session timeout.

**Comment by mrchristopher124** [comment]
Note also that they now have what they call "Standard Events":

https://docs.localytics.com/dev/ios.html#standard-events-ios

**Comment by ladanazita** [comment]
@mrchristopher124 This is now live!

**Comment by mrchristopher124** [comment]
@ladanazita thank you 👍
